import { StyleSheet } from 'react-native';

export const appStyles = StyleSheet.create({
  homeContainer: {
    flex: 1,
    backgroundColor: '#0a0f1e',
    paddingHorizontal: 20,
    gap: 14,
  },
  title: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '700',
    marginTop: 8,
  },
  subtitle: {
    color: '#a6b4d0',
    fontSize: 16,
    marginBottom: 6,
  },
  card: {
    backgroundColor: '#121a30',
    borderWidth: 1,
    borderColor: '#1f2a48',
    borderRadius: 12,
    padding: 16,
    marginBottom: 4,
  },
  cardTitle: {
    color: '#8aa0d2',
    fontSize: 12,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  cardStatusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
    gap: 10,
  },
  cardStatusLabel: {
    color: '#d7e3ff',
    fontSize: 15,
    fontWeight: '600',
    flex: 1,
  },
  cardStatusValue: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  linkButton: {
    backgroundColor: '#1a73e8',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  linkButtonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '600',
  },
  screenContainer: {
    flex: 1,
    backgroundColor: '#0a0f1e',
    paddingHorizontal: 20,
  },
  screenTitle: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 12,
  },
  screenBody: {
    color: '#dbe7ff',
    fontSize: 16,
    marginBottom: 8,
  },
  screenHint: {
    color: '#9fb2d8',
    fontSize: 14,
    marginBottom: 20,
  },
  modelsCard: {
    backgroundColor: '#121a30',
    borderWidth: 1,
    borderColor: '#1f2a48',
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    maxHeight: 300,
    overflow: 'hidden',
  },
  modelsList: {
    maxHeight: 220,
  },
  modelsListContent: {
    paddingBottom: 4,
  },
  modelsTitle: {
    color: '#dbe7ff',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
  },
  modelsSummary: {
    color: '#9fb2d8',
    fontSize: 12,
    marginBottom: 10,
  },
  modelsEmpty: {
    color: '#9fb2d8',
    fontSize: 13,
  },
  modelRow: {
    backgroundColor: '#0d1428',
    borderWidth: 1,
    borderColor: '#23335a',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  modelHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  modelName: {
    color: '#e8f0ff',
    fontSize: 13,
    fontWeight: '700',
  },
  modelBadge: {
    color: '#8fb6ff',
    fontSize: 10,
    fontWeight: '700',
    borderWidth: 1,
    borderColor: '#3d62a8',
    borderRadius: 99,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  modelFile: {
    color: '#b8c7e6',
    fontSize: 11,
    lineHeight: 16,
  },
  refreshButton: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2a3b62',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  refreshButtonText: {
    color: '#dbe7ff',
    fontSize: 14,
    fontWeight: '600',
  },
  actionButton: {
    backgroundColor: '#1a73e8',
    minHeight: 50,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonDisabled: {
    backgroundColor: '#51607a',
  },
  actionButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  secondaryButton: {
    marginTop: 14,
    minHeight: 48,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2a3b62',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: '#dbe7ff',
    fontSize: 15,
    fontWeight: '600',
  },
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: '#000',
  },
  permissionText: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 16,
  },
  button: {
    backgroundColor: '#1a73e8',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  buttonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  banner: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 20,
    paddingBottom: 14,
  },
  bannerText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  controls: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
    paddingTop: 16,
  },
  scanButton: {
    backgroundColor: '#1a73e8',
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  scanButtonDisabled: {
    backgroundColor: '#555',
  },
  scanButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  loadingHint: {
    color: '#ccc',
    fontSize: 12,
    marginTop: 8,
  },
  backFab: {
    position: 'absolute',
    left: 12,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#3d3d3d',
  },
  backFabText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  detectionBox: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: '#4dc3ff',
    borderRadius: 6,
    backgroundColor: 'rgba(77,195,255,0.08)',
  },
  detectionTag: {
    position: 'absolute',
    top: -24,
    left: 0,
    backgroundColor: 'rgba(20,30,45,0.85)',
    borderWidth: 1,
    borderColor: '#4dc3ff',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    maxWidth: 180,
  },
  detectionTagText: {
    color: '#dff5ff',
    fontSize: 11,
    fontWeight: '700',
  },
});
